### ISSUE TITLE
Several things...

### ISSUE THREAD

**Issue by elibarzilay** [m-manu/rsync-sidekick#1]
I've been suffering years of "*sigh*, I'll just run rsync and suffer the extra hours" and I finally decided to do something about it.  I always thought that a good approach would be some kind of a pre-script that crawls over the directories on both sides and performs the needed renames -- to be followed by the actual `rsync`.  When I hacked most of this (as a simple `bash` script), I thought that it would be a good idea to post something about it so maybe someone will do it properly, so I went back to [one of the old SO questions about it](https://serverfault.com/questions/489289/handling-renamed-files-or-directories-in-rsync), and I was surprised that you've done this at almost the exact same time!  (Well, three months ago, but on a scale of the >7 years that this question was posted, it can be considered the same time :)

Anyway, I've looked at your code very briefly (I don't know much go), and there are several important things that I think would make it be truly useful.  Take the following as enthusiastic suggestions, but feel free to ignore them if it doesn't fit your goal...

1. The very first thing is needed to make people comfortable running unknown code that crawls over their precious media collections is a good explanation.  You do say the important point -- that it doesn't delete anything -- but a brief description that this is guessing where files should move to before running `rsync` should put people more at ease.

2. It should also mention that while files are not deleted, they *are* moved around.  (Which should not scare people with the added explanation that I suggested above, and also see below.)

3. Following the same line further, you should mention the option of doing nothing and generating a script instead.  As a random viewer, I'd feel much more comfortable running code that will not *do* anything and instead spit out a script that I can inspect and run.  (And BTW, it would be nice to be able to spit out the script instead of always dumping it into a file.)

4. Yet more in this direction: you should really have some `--dry-run` mode that is similar but describing the operations it would have done instead.

5. Finally (in the explanation section of this suggestion), saying that this is intended to run before an `rsync` would also be good to mention.  Basically, the fact that even if there are some bugs or some unknown situations that it would mishandle, then the following `rsync` would straighten things out -- so the most that you might lose is some time with `rsync` doing more work than it could have.  (Which is likely still much less than not using this thing at all.)

(The following are functionality suggestions...)

6. Not clear to me whether you handle it well or not (looks like you don't), but dealing with file swapping gracefully would be good too.  Something like swapping two (or more) existing files in the source tree, which requires a temporary file rename in the destination.

7. Looks like the metadata that you're collecting for file identity is just the file size, which can be too weak.  What I did in my bash hack is using the file size as well as the first+last N bytes of the file (and a middle-block would be a good addition).  This makes it much more reliable and still relatively fast, though slower than just the sizes since it requires actually opening and reading from the files.  It could be placed behind a command-line flags for cases where you don't want to pay the extra penalty of actually doing contents IO as a global decision of whether to include that in the metadata (possibly with an adjustable setting of what N you want to use, or even being able to specify a complete-file checksum).

8. Something that you're not doing and is a blocker for me: looks like you're only handling two *local* directories.  The main reason I finally gave up and did my hack was a sync of media to a remote machine.  (I also do local syncs, but for that I don't mind the extra time as much.)  This might require some more tweaking of the code, since you won't be able to propagate timestamp changes as easily.  (My script doesn't do that at all, since that's much cheaper for `rsync` to do.)

   BTW, the way that I did this was to assume that the script lives in the target machine in the same place, and then to collect remote information it uses `ssh remot "$0" ...` so everything is still conveniently in one script.

9. And lastly, it would be nice if it was easier to use it for random bystanders.  For example, providing a statically-linked executable, and/or a script that wraps a docker usage, and/or a mode that runs both this and then `rsync` in one shot.

**Comment by m-manu** [comment]
Thanks for a lot for your inputs! I see that you've taken time to provide them and I appreciated it. 

Here are my responses:

1. It's mentioned so in the README -- But sure will highlight that.
2. Sure, will add in README
3. There is a command line option to do that already. Run `rsync-sidekick -help` to know which.
4. Sure, will add in README
5. Sure, will add in README
6. Sure, I will add this in code.
7. What you asked already exists! Currently, file uniqueness is computed using crucial bytes (combination of first 2 KiB, middle 4 KiB and last 2 KiB) + file size + extension (see: [file_hash.go](https://github.com/m-manu/rsync-sidekick/blob/main/service/file_hash.go)) -- It gave me the same uniqueness as that of SHA-256 for over a ~175k files last time I tested. It's fairly solid.
8. Yes, that's not handled and probably will not be. I'm handling remote by mounting them locally. Timestamp things work.
9. Sure, executable for popular OSes I can provide. It's already dockerized. Let me consider the 'one shot' thing.

**Comment by elibarzilay** [comment]
1. I know, I'm saying that it should be more explicit.
2. -
3. Yeah, but it's not in the readme...
4. -
5. -
6. -
7. Ah, good -- I missed that.
8. That's a shame, since it's a very common use case.  (Since rsync knows how to work over ssh, doing so for syncing is generally much faster than doing it locally over a remote-mount.)
9. -

**Comment by wapsi** [comment]
This tool is wonderful but I was also wondering if it's possible to perform the remote sync over SSH somehow? I see the point 8. here mention this but is the best approach to use SSHFS to mount the remote directory over SSH and then execute this tool? How is the performance then? Is it transferring the whole while in the background for the actual comparsion if I'm doing that (so it'll lose the actual benefit this tool gains)?

**Comment by elibarzilay** [comment]
@wapsi I haven't really tried it, but performance should be pretty horrible over an sshfs mount.  (And the reason I didn't try it is because I'm pretty sure it would be very bad.)

What I do get from time to time, is a long lag when I accidently get `git` to do something in an sshfs mount: accessing many small files is generally an extreme bad case.  But more than that: rsync is doing things like comparing files and/or parts of files to minimize copying -- using a remote mount will (a) kill that since just looking at these files already require passing the bits through the wire; and (b) it might even make it worse since naive code that does "if these dest bits are different, copy them from the source" over a remote mount will transfer the bits once for the test, and again for the copy.

**Comment by wapsi** [comment]
Yeah, thanks.

BTW: Are you willing to share your solution / script? I'm taking weekly backups of my files over the internet and I'm facing issues by time to time when I rename/move directories under my Videos directory (for example) and it's stupid when Rsync re-transfers the same files and then deletes the existing ones even they're the very same files, just renamed/moved ones...

**Comment by elibarzilay** [comment]
@wapsi, sure, the whole script is kind of redundant (it's a personal script that I use to wrap `rsync` in some sanity and some convenience), but I'm just dumping the whole thing here.  The relevant bits are from `get_hash()` through to `do_sync_moves()`.

Note that it's not actually doing the move, just prints them (the `printf "Actions:\n"` line) -- it's pretty new so I'd rather eyeball the action for a while before I make it do them (even though like this project, it's relatively safe since screwing up will likely be patched over by the `rsync` run that follows).  There's also some trickiness in how the script invokes itself on the remote host with a special argument as a hacked bash-form of RPC...

And of course, requires some bash knowledge to know how to pull the relevant bits out.  (If you don't know enough bash, it might be easier to just use the script as-is; email me in that case and I'll tell you how it's used.  Or maybe even make a one-script project for it...)

```bash
#!/usr/bin/env bash

dry=0; moves=0; _do=""

cmd=(rsync -avhz -P -e ssh -H)
cmd+=(--delete)

set -eu
while true; do
  if   [[ "x$1" = x-DO::*- ]]; then _do="${1#-DO::}"; _do="${_do%-}"
  elif [[ "x$1" = x-*  ]]; then cmd+=("$1")
  elif [[ "$1" = moves ]]; then moves=1
  elif [[ "$1" = dry   ]]; then dry=1
  elif [[ "$1" = slow  ]]; then cmd+=(--bwlimit 100k)
  elif [[ "$1" =~ [0-9]+[bBkKmM]? ]]; then cmd+=(--bwlimit "$1")
  else break; fi
  shift 1
done

failwith() { echo "error: $*" 1>&2; exit -1; }

run() {
  printf ">>>"; printf " %q" "${cmd[@]}" "$@"; printf "\n"
  if ((dry)); then return; fi
  set +e
  "${cmd[@]}" "$@" & bg="$!"
  killbg() { kill -15 "$bg"; wait "$bg"; exit "$!"; }
  trap killbg INT
  while sleep 2; do
    limit=""; read -t 1 limit
    if ! kill -0 "$bg" >&/dev/null; then wait "$bg"; exit "$?"; fi
    if [[ "$limit" =~ [0-9]+[bBkKmM]? ]]; then
      kill -15 "$bg"; wait "$bg"
      "${cmd[@]}" --bwlimit "$limit" "$@" & bg="$!"
    fi
  done
}

tilde() {
  if [[ "$1" != "$HOME"/* ]]; then echo $1
  else echo "~${1#$HOME}"; fi
}

get_hash() {
  hash="$({ stat --format="%s" "$f"; head -c 1000 "$f"; tail -c 1000 "$f"
          } | md5sum)"
  echo "${hash%% *}" "${PFX:-}${f#./}"
}
get_hashes1() {
  for f; do get_hash "$f"; done
}
get_hashes() {
  if [[ -d "$1" ]]; then
    (cd "$1"; find . -type f -exec "$0" -DO::get_hashes1- {} +)
  elif [[ "$1" = *:* ]]; then
    ssh "${1%%:*}" PFX="R:" "$0" -DO::get_hashes- "${1#*:}"
  else
    failwith "get_hashes: \"$1\" not found"
  fi
}
if [[ -n "$_do" ]]; then "$_do" "$@"; exit; fi

do_sync_moves() {
  echo "Syncing moves from $1 to $2"
  tmp="/tmp/myrsync-$$"; echo -n > "$tmp"
  for d; do
    echo "  Getting hashes of $d..."; get_hashes "$d" >> "$tmp"
  done
  sort "$tmp" > "$tmp."; mv "$tmp." "$tmp"; echo "xxxx xxxx" >> "$tmp"
  curhash=""; lfiles=(); rfiles=(); actions=(); dontknow=()
  addfile() {
    if [[ "$1" = "R:"* ]]; then rfiles+=("${1#R:}"); else lfiles+=("$1"); fi
  }
  lfiles_in_rfiles() {
    if [[ "${#lfiles[@]}" = 0 ]]; then return 0; fi
    local f rfilescolons="$(printf ": :%s" "${rfiles[@]}"): :"
    for f in "${lfiles[@]}"; do
      if [[ "$rfilescolons" != *": :$f: :"* ]]; then return 1; fi
    done
    return 0
  }
  while IFS= read -r l; do
    hash="${l%% *}"; file="${l#* }"
    if [[ "$curhash" = "$hash" ]]; then addfile "$file"; continue; fi
    lnum="${#lfiles[@]}"; rnum="${#rfiles[@]}"
    if lfiles_in_rfiles || [[ "$rnum" = "0" ]] || \
       [[ "$lnum" = 1 && "$rnum" = 1 \
          && "${lfiles[0]}" = "${rfiles[0]}" ]]; then :
    elif [[ "$lnum$rnum" != "11" ]]; then
      dontknow+=(
        "$(printf "${#lfiles[@]} lfiles:\n"; printf "  %s\n" "${lfiles[@]}"
           printf "${#rfiles[@]} rfiles:\n"; printf "  %s\n" "${rfiles[@]}")")
    else
      actions+=("$(printf "mv %q %q\n" "${rfiles[@]}" "${lfiles[@]}")")
    fi
    curhash="$hash"; lfiles=(); rfiles=(); addfile "$file"
  done < "$tmp"
  rm -f "$tmp"
  if [[ "${#actions[@]}" != "0" ]]; then
    printf "Actions:\n"; printf "  %s\n" "${actions[@]}"
  fi
  if [[ "${#dontknow[@]}" != "0" ]]; then
    printf "Don't know what do do about:\n"; printf "  %s\n" "${dontknow[@]}"
  fi
  if [[ "${#actions[@]}" != "0" ]]; then
    failwith "running these actions is not implemented"
  elif [[ "${#dontknow[@]}" != "0" ]]; then
    failwith "need to handle the above cases"
  fi
}

do_sync() {
  op="$1"; shift; rem="$1"; shift; loc="$1"; shift
  case "$op" in
    ( from ) from="$rem" to="$loc" ;;
    ( to   ) from="$loc" to="$rem" ;;
    ( *    ) failwith "unknown operation \"$op\"" ;;
  esac
  if ((moves)); then do_sync_moves "$from" "$to"; fi
  printf "Copying from \"%s\" to \"%s\"\n" "$(tilde "$from")" "$(tilde "$to")"
  run "$from" "$to"
}

if [[ "$1" != "from" && "$1" != "to" ]]; then run "$@"; exit; fi

op="$1"; shift; host="$1"; shift

if [[ "$host" = *:* ]]; then
  if [[ "$#" != "1" ]]; then failwith "explicit mode requires one directory"; fi
  rdir="${host#*:}"; host="${host%%:*}"; ldir="$(realpath -e "$1")"; shift
  rdir="${rdir%/}/" ldir="${ldir%/}/"
  do_sync "$op" "$host:$rdir" "$ldir"
else
  for dir; do
    if [[ "$dir" != /* ]]; then
      if [[ "${dir%/}" != "." && "${dir%/}" != ".." \
            && -d "$HOME/$dir" ]]; then dir="$HOME/$dir"
      elif [[ -d "$dir" ]]; then
        hdir="$(realpath -m "$dir")"
        if [[ "$hdir" != "$HOME"/* ]]; then failwith "\"$dir\" not found"; fi
        read -p "\"~/$dir\" not found, use \"$(tilde "$hdir")\"? " -n 1 R; echo
        case "$R" in ([yY]*) dir="$hdir";; (*) dir="$HOME/$dir";; esac
      fi
    fi
    dir="${dir%/}/"
    hdir="$(tilde "$dir")"
    if [[ ! -d "$dir" ]]; then
      read -p "\"$hdir\" does not exist, create? " -n 1 R; echo
      case "$R" in ([yY]*) :;; (*) exit -1;; esac
      if ((!dry)); then mkdir "$dir"; fi
    fi
    do_sync "$op" "$host:$hdir" "$dir"
  done
fi
```

**Comment by wapsi** [comment]
Thanks!

Actually I found one alternative solution from here: http://www.pkrc.net/detect-inode-moves.html and I modified / improved the script to meet my needs better and then I made smart-backup.sh script which wraps up the using of that Python script and Rsync, you can find my code from here: https://github.com/wapsi/smart-rsync-backup

**Comment by m-manu** [comment]
@wapsi Frankly, this tool gives a pretty decent performance over SSHFS. Primarily because, `rsync-sidekick` isn't doing an actual transfer of files and it's just moving around files and reading 'crucial bytes') -- for which SSHFS is more than enough.
For doing the actual file transfer later (using `rsync`), I would not recommend using SSHFS, though.

(Cc: @elibarzilay)

**Comment by kzar79** [comment]
Dear @m-manu, I never programmed in Go, so unfortunately I cannot help you directly, otherwise I would write a pull request.

But reading your code it seems that you need to make only a couple of changes to make it work remotely through SSH (or even manually) without the need of SSHFS, and therefore transferring only the minimum amount of data (like RSYNC does).

It would be a great improvement, given that still doesn't exist a (decent) solution to this problem (without maintaining databases or other kind of tricks), and your program is actually the best I found so far.

The problem with SSHFS in fact is that it cannot read only "crucial bytes" and is also very slow in reading directory contents (it relies on SFTP which is a file transfer protocol, not designed for this kind of access). Yes one could use NFS or CIFS but... an RSYNC-like solution is much better (your program is called _rsync-sidekick_ for a reason!)

What I propose is only two small changes to your program. The idea is to have a second copy of it installed remotely, which will be called only two times (automatically or manually).

The first change would be in your `rsyncSidekick` function. Now you scan both the `sourceDirPath` and the `destinationDirPath`. You could make a `scanAndSerializePath` function that only scans the `destinationDirPath` and serializes the results in a file. 

So the program is first invoked remotely to create the serialized list of destination path.

That list is then transferred to the source computer (automatically or manually), and the program is invoked again passing that file instead of the destination path (or resumes after retrieving the resulting file from the remote process). 

In that case the program deserializes the list and then passes that list to the `rsyncSidekick` function. In the _local_ mode (when both folders are local) you just need to first scan the `destinationDirPath` and then call the `rsyncSidekick` function passing the list, so to modify that function you only need to remove lines 35-38.

The other change would be in the `ComputeSyncActions` function. Now you call the `buildIndex` function both for the `orphansAtSource` and the `candidatesAtDestination`.

In the _remote_ mode you could instead serialize the `candidatesAtDestination` in a file and invoke again the program remotely passing that file. The remote program would only call the `buildIndex` function and serialize the resulting `candidateFilesToDigests` map to a file, which would be transferred to the source. 

This operation too can be done automatically or manually. In the first case (automatically) the local program would resume after receiving the serialized map, in the second case the user would call the program locally again passing the file.

At that point we are at row 102 of `ComputeSyncActions`, the local program has all the information it needs to finish. It can write a script (which already does) and save it to a file and (if automatic) copy and call it on the remote machine.

It is less complex than it seems. In practice you need to refactor lines 35-38 of `rsyncSidekick` and lines 80-92 of `ComputeSyncActions` to create two new functions, plus adding serialization and deserialization and some parameters to the program so it knows in what phase it is and what is supposed to do. 

I would be happy with this _manual_ way. It could be easily scripted to do the remote->copy->local->copy->remote->copy->local thing without any need to automatically invoke the remote copy from within the local program itself. If needed, I would be happy then to share such a script.

**Comment by elibarzilay** [comment]
@wapsi, yes, using inodes can be useful in some generally more limited cases -- the difference between this and using a checksum of parts of the file is not too big, since it can be seen as an alternative identity hash to use.  But if using inodes is fine for your case, then there is another solution somewhere that creates a hidden directory of hard-links for all files, with the overall result of rsync doing all of the work itself with no other scripts needed.

@m-manu: like @kzar79 said, sshfs is really not a good solution since even if it doesn't retrieve the whole file for its cache, it still transfers the to-be-hashed contents.  rsync specifically avoids this extra cost by having it execute itself on the remote host which is how it can get the hashes without fetching any actual contents.

**Comment by m-manu** [comment]
@elibarzilay Makes sense. Will take it up when possible.

**Comment by m-manu** [comment]
@kzar79 Thanks for the inputs. Will take it up when possible.
